<?php

namespace AppBundle\Repository;

use Pagerfanta\Adapter\DoctrineORMAdapter;

/**
 * ArtistRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArtistRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @return DoctrineORMAdapter
     */
    public function findAllWithTracksPagerAware()
    {
        $qb = $this->createQueryBuilder('artists');
        $qb
            ->leftJoin('artists.tracks', 'tracks')
            ->select('artists', 'tracks')
        ;

        return new DoctrineORMAdapter($qb);;
    }
}
