<?php

namespace AppBundle\Repository;

use AppBundle\Entity\User;
use Doctrine\ORM\EntityRepository;

/**
 * PlaylistRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlaylistRepository extends EntityRepository
{
    public function findPublic()
    {
        $qb = $this->createQueryBuilder('p');
        $qb
            ->leftJoin('p.tracks', 't')
            ->select('p', 't')
            ->where(
                $qb->expr()->eq('p.public', true)
            );

        return $qb->getQuery()->execute();
    }

    public function findOwn(User $user)
    {
        $qb = $this->createQueryBuilder('p');
        $qb
            ->leftJoin('p.tracks', 't')
            ->select('p', 't')
            ->where(
                $qb->expr()->eq('p.owner', ':owner')
            )
            ->setParameter('owner', $user)
        ;

        return $qb->getQuery()->execute();
    }
}
