<?php

namespace AppBundle\Repository;

/**
 * TrackRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TrackRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAllWithArtist()
    {
        $qb = $this->createQueryBuilder('tracks');
        $qb
            ->leftJoin('tracks.artist', 'artists')
            ->select('tracks', 'artists')
        ;

        return $qb->getQuery()->execute();
    }

    public function findWithArtist($trackId)
    {
        $qb = $this->createQueryBuilder('tracks');
        $qb
            ->leftJoin('tracks.artist', 'artists')
            ->select('tracks', 'artists')
            ->where($qb->expr()->eq('tracks.id', ':trackId'))
            ->setParameter('trackId', $trackId)
        ;

        return $qb->getQuery()->getOneOrNullResult();
    }

}
