security:
    providers:
        users:
            entity:
                class: AppBundle\Entity\User
                property: username

    encoders:
        AppBundle\Entity\User: bcrypt

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern: ^/
            anonymous: ~
            provider: users
            form_login:
                login_path: app_security_login
                check_path: app_security_login

            logout:
                path: app_security_logout
                target: homepage

    access_control:
        - { path: ^/(tracks|artists)/(new|\d+), roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/, roles: IS_AUTHENTICATED_ANONYMOUSLY }