security:
    providers:
        users:
            entity:
                class: AppBundle\Entity\User
                property: username

    encoders:
        AppBundle\Entity\User: bcrypt

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern: ^/
            anonymous: ~
            provider: users
            # activate different ways to authenticate

            http_basic: ~
            # http://symfony.com/doc/current/book/security.html#a-configuring-how-your-users-will-authenticate

            # form_login: ~
            # http://symfony.com/doc/current/cookbook/security/form_login_setup.html

    access_control:
        - { path: ^/(tracks|artists)/(new|\d+), roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/, roles: IS_AUTHENTICATED_ANONYMOUSLY }

# [
#    'access_control' => [
#      ['path' => '...', 'roles' => '...'],
#      ['path' => '...', 'roles' => '...']
#    ]
# ]
#