homepage:
    path: /
    defaults:
        _controller: AppBundle:Playlist:index

app_playlist_view:
    path: /{id}
    defaults:
        _controller: AppBundle:Playlist:view
    requirements:
        id: \d+

app_playlist_new:
    path: /new
    defaults:
        _controller: AppBundle:Playlist:edit

app_playlist_edit:
    path: /{id}/edit
    defaults:
        _controller: AppBundle:Playlist:edit
    requirements:
        id: \d+

app_track_index:
    path: /tracks/
    defaults:
            _controller: AppBundle:Track:index

app_track_view:
    path: /tracks/{id}
    defaults:
        _controller: AppBundle:Track:view
    requirements:
        id: \d+

app_track_new:
    path: /tracks/new
    defaults:
        _controller: AppBundle:Track:edit

app_track_edit:
    path: /tracks/{id}
    defaults:
        _controller: AppBundle:Track:edit
    requirements:
        id: \d+

app_track_addtoplaylist:
    path: /tracks/{id}/add
    defaults:
        _controller: AppBundle:Track:addToPlaylist
    requirements:
        id: \d+

app_artist_index:
    path: /artists/
    defaults:
        _controller: AppBundle:Artist:index

app_artist_new:
    path: /artists/new
    defaults:
        _controller: AppBundle:Artist:edit

app_artist_edit:
    path: /artists/{id}
    defaults:
        _controller: AppBundle:Artist:edit
    requirements:
        id: \d+
    methods: [GET, POST]

app_artist_delete:
    path: /artists/{id}
    defaults:
        _controller: AppBundle:Artist:delete
    requirements:
        id: \d+
    methods: [DELETE]

app_security_register:
    path: /register
    defaults:
        _controller: AppBundle:Security:register

app_security_logout:
    path: /logout

app_security_login:
    path: /login
    defaults:
        _controller: AppBundle:Security:login